name: CD

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  pypi:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.0.0
      - run: uv build
      - if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  build-windows:
    name: Build Windows installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.0.0
        with:
          python-version: "3.13"
      - run: uv build --wheel --out-dir installer
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
      - name: Install constructor
        shell: bash -el {0}
        run: conda install -n base -y -c conda-forge constructor nsis
      - name: Build installer
        shell: bash -el {0}
        run: conda run -n base constructor installer/ --output-dir installer-dist
      - uses: actions/upload-artifact@v7
        with:
          name: body-eye-sync-windows-installer
          path: installer-dist/*.exe
          if-no-files-found: error
