name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v6
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          python-version: "3.13"
      - run: uv sync --only-group dev
      - run: uv run zensical build --clean
      - uses: actions/upload-pages-artifact@v5
        with:
          name: github-pages-${{ github.run_id }}-${{ github.run_attempt }}
          path: site
      - uses: actions/deploy-pages@v5
        id: deployment
        with:
          artifact_name: github-pages-${{ github.run_id }}-${{ github.run_attempt }}
